# Generated by Django 2.0.2 on 2018-05-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='test',
        ),
    ]
