# Generated by Django 2.0.2 on 2018-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_reader', '0002_remove_aircraft_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='yearbuilt',
            field=models.IntegerField(blank=True, db_column='YearBuilt', max_length=4, null=True),
        ),
    ]
