# Generated by Django 2.0.2 on 2018-06-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestLocalMake',
        ),
    ]
