# Generated by Django 2.0.2 on 2018-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_delete_testlocalmake'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test111', models.CharField(max_length=50)),
            ],
        ),
    ]
