# Generated by Django 2.0.2 on 2018-06-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_testmig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMig',
        ),
    ]
