# Generated by Django 2.0.2 on 2018-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0004_delete_testmig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewerTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_char', models.CharField(max_length=50)),
            ],
        ),
    ]
