# Generated by Django 2.0.2 on 2018-06-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_newertest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewerTest',
        ),
    ]
