# Generated by Django 2.0.2 on 2018-05-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fussion_charts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
