# Generated by Django 2.0.2 on 2018-05-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_reader', '0002_remove_aircraft_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPlanesLanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id_landed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_aircraft', to='database_reader.Flights')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_name', models.CharField(max_length=150)),
            ],
        ),
    ]
