# Generated by Django 2.0.2 on 2018-05-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_reader', '0002_remove_aircraft_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPlanesLanded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times_landed', models.IntegerField()),
                ('aircraft_id_landed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_aircraft', to='database_reader.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='MostPlanesTakeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_take_offs', models.IntegerField()),
                ('aircraft_id_take_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_aircraft', to='database_reader.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_name', models.CharField(max_length=150)),
                ('records_processed', models.IntegerField()),
                ('time_last_updated', models.DateTimeField()),
            ],
        ),
    ]
