# Generated by Django 2.0.2 on 2018-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingsDayTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_the_day', models.IntegerField()),
                ('number_of_planes', models.BigIntegerField()),
            ],
        ),
    ]
