# Generated by Django 2.0.2 on 2018-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='records_processed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
