# Generated by Django 2.0.2 on 2018-05-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_stats_records_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostplaneslanded',
            name='aircraft_id_landed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_aircraft', to='database_reader.Aircraft'),
        ),
    ]
