# Generated by Django 2.0.2 on 2018-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20180518_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostplaneslanded',
            name='number_of_times_landed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
