# Generated by Django 2.0.2 on 2018-05-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_reader', '0002_remove_aircraft_test'),
        ('charts', '0004_mostplaneslanded_number_of_times_landed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPlanesTakeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_take_offs', models.IntegerField()),
                ('aircraft_id_take_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_aircraft', to='database_reader.Aircraft')),
            ],
        ),
    ]
